name: Publish container to ACR
on:
  pull_request:
    types:
      - closed
    paths:
      - "Kubernetes/fastapi-101-main/**"
#   push:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build . -t fastapi-101
        working-directory: ./Kubernetes/fastapi-101-main

      - name: Save Docker image
        run: |
          docker save fastapi-101:latest \
          -o fastapi-101.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: fastapi-image
          path: fastapi-101.tar

  Push:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: fastapi-image

      - name: Load Docker image
        run: |
          docker load -i fastapi-101.tar

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_REGISTRY }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Tag image
        run: |
          docker tag fastapi-101:latest ${{ secrets.ACR_REGISTRY }}.azurecr.io/fastapi-101:latest

      - name: Push image
        run: |
          docker push ${{ secrets.ACR_REGISTRY }}.azurecr.io/fastapi-101:latest

  Deploy:
    runs-on: ubuntu-latest
    env:
      resource_group: ${{ vars.resource_group }}
      cluster_name: ${{ vars.cluster_name }}
    needs: Push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

      - name: Set AKS Context
        uses: azure/aks-set-context@v2
        with:
          resource-group: ${{ env.resource_group }}
          cluster-name: ${{ env.cluster_name }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: sadasdas
        uses: azure/k8s-deploy@v4
        with: 
          namespace: default
          mainfests: |
            Kubernetes/fastapi-101-main/deployment.yaml
          images: ${{ secrets.ACR_REGISTRY }}.azurecr.io/fastapi-101:latest
